let data_2d = [
    {
        src:'/img/services/2D/02.jpg',
        thumbnail:'/img/services/2D/thumbnail/2D场景原画_设计01-1.jpg',
        parameter:'data_2d_01',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/03.jpg',
        thumbnail:'/img/services/2D/thumbnail/2D场景原画_设计02-1.jpg',
        parameter:'data_2d_02',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/04.jpg',
        thumbnail:'/img/services/2D/thumbnail/2D场景原画_设计04-1.jpg',
        parameter:'data_2d_03',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/05.jpg',
        thumbnail:'/img/services/2D/thumbnail/2D场景原画_设计08-1.jpg',
        parameter:'data_2d_04',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/06.jpg',
        thumbnail:'/img/services/2D/thumbnail/2D场景原画_科幻类_自研_近未来风格5-1.jpg',
        parameter:'data_2d_05',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/07.jpg',
        thumbnail:'/img/services/2D/thumbnail/2D场景原画_科幻类_自研_近未来风格6-1.jpg',
        parameter:'data_2d_06',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/01.jpg',
        thumbnail:'/img/services/2D/thumbnail/1.jpg',
        parameter:'data_2d_07',
        css:'',
        title:''
    },
    {
        src:'/img/services/2D/08.jpg',
        thumbnail:'/img/services/2D/thumbnail/36fbda2819a908ee60c527bb81e1f7a-1.jpg',
        parameter:'data_2d_08',
        css:'',
        title:''
    },
]

let data_3d = [
    {
        src:'/img/services/3D/01.jpg',
        thumbnail:'/img/services/3D/thumbnail/01.jpg',
        parameter:'data_3d_01',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/02.jpg',
        thumbnail:'/img/services/3D/thumbnail/02.jpg',
        parameter:'data_3d_02',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/03.jpg',
        thumbnail:'/img/services/3D/thumbnail/03.jpg',
        parameter:'data_3d_03',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/04.jpg',
        thumbnail:'/img/services/3D/thumbnail/04.jpg',
        parameter:'data_3d_04',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/05.jpg',
        thumbnail:'/img/services/3D/thumbnail/05.jpg',
        parameter:'data_3d_05',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/06.jpg',
        thumbnail:'/img/services/3D/thumbnail/06.jpg',
        parameter:'data_3d_06',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/07.jpg',
        thumbnail:'/img/services/3D/thumbnail/07.jpg',
        parameter:'data_3d_07',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/08.jpg',
        thumbnail:'/img/services/3D/thumbnail/08.jpg',
        parameter:'data_3d_08',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/09.jpg',
        thumbnail:'/img/services/3D/thumbnail/09.jpg',
        parameter:'data_3d_09',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/10.jpg',
        thumbnail:'/img/services/3D/thumbnail/10.jpg',
        parameter:'data_3d_10',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/11.jpg',
        thumbnail:'/img/services/3D/thumbnail/11.jpg',
        parameter:'data_3d_11',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/12.jpg',
        thumbnail:'/img/services/3D/thumbnail/12.jpg',
        parameter:'data_3d_12',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/13.jpg',
        thumbnail:'/img/services/3D/thumbnail/13.jpg',
        parameter:'data_3d_13',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/14.jpg',
        thumbnail:'/img/services/3D/thumbnail/14.jpg',
        parameter:'data_3d_14',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/15.jpg',
        thumbnail:'/img/services/3D/thumbnail/15.jpg',
        parameter:'data_3d_15',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/16.jpg',
        thumbnail:'/img/services/3D/thumbnail/16.jpg',
        parameter:'data_3d_16',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/17.jpg',
        thumbnail:'/img/services/3D/thumbnail/17.jpg',
        parameter:'data_3d_17',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/18.jpg',
        thumbnail:'/img/services/3D/thumbnail/18.jpg',
        parameter:'data_3d_18',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/19.jpg',
        thumbnail:'/img/services/3D/thumbnail/19.jpg',
        parameter:'data_3d_19',
        css:'',
        title:''
    },
    {
        src:'/img/services/3D/20.jpg',
        thumbnail:'/img/services/3D/thumbnail/20.jpg',
        parameter:'data_3d_20',
        css:'',
        title:''
    },
]

let data_animation = [
    {
        src:'/img/services/Thumbnail.png',
        thumbnail:'/img/services/Thumbnail.png',
        parameter:'data_animation_01',
        css:'',
        title:''
    },
]